name: update-ranking

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [master]
  schedule:
    - cron: 0 16 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.10


      - name: Install Python
        run: |
          pip3 install -r requirements.txt

      - name: get ranking
        run: |
          python3 ranking.py
      
      - name: commit
        run: |
          git config --global user.email wbenature@163.com
          git config --global user.name Benature
          git add .
          git commit -m "update daily" -a
          # git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
